# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saqib Azim
full_name: Saqib Azim
email: azimsaqib10@gmail.com
email2: saqib.azim.no@hitachi.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saqib1707.github.io" # the base hostname & protocol for your site
github_username:  saqib1707
# twitter_username: kalpeshk2011
linkedin_username: saqib-azim-760632126
# stackoverflow: 5080995/martianwars
include: ['_pages']
footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
